<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<link rel="stylesheet" href="css/normalize-3.0.3.min.css">
	<link rel="stylesheet" href="css/style.css"/>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
	 <link href="https://fonts.googleapis.com/css?family=Amatic+SC" rel="stylesheet">
	 <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet"> 
	<title>Blog</title>
</head>
<body>
	<header>
	<h1><i class="fas fa-microphone"></i>encore un blog ?! #nonmaisallo</h1>
	<nav>
		<a href="index.php"><i class="fas fa-home"></i> Accueil</a>
		<a href="admin.php"><i class="fas fa-cogs"></i> Administration</a>
	</nav>
	</header>
	<main>
	 	<?php include $template.'.phtml' ?>
	</main>
	<footer>
		<p>Le blog des élèves de la 3w Academy</p>
	</footer>
</body>
</html>